### ISSUE TITLE
Should a short delay default to 2 rather than error?

### ISSUE THREAD

**Issue by lurkio** [mungre/img2beeb#4]
https://github.com/mungre/img2beeb/blob/2bbed5bc6d83bf2875f584e3e976dde246dd1002/src/Program.cs#L221

I've done this to get the [Lamborghini GIF](https://stardot.org.uk/forums/viewtopic.php?f=11&t=13294&p=243355&hilit=lamborghini#p243355) to convert:

                Debug.Assert(frameDelay >= 0 && frameDelay < 256);
                if (frameDelay < 3)
                {
                    frameDelay = 2;
                }
                if (frameDelay >= 256)
                {
                    throw new ApplicationException("The frame delay is too long!");
                }

**Comment by mungre** [comment]
Hypothetically, you might speed up the BASIC or run it on a faster emulator or rewrite it in assembly language or whatever, so the delay would no longer be an issue.  And then you would need to reprocess any files in which the delay had been forced to 2 to give them the correct delay.

I think a better design would be to display a warning when the delay is too short (even better if the warning is only shown once per file, like `patchWarning`) and then write the file with the real delay.  The BASIC program would be amended to cope with short delays.  If this slowed it down noticeably the BASIC could preprocess the data before it started the animation.

**Comment by mungre** [comment]
I was bored so I rewrote the animation using assembly language.  Given that the screen only updates fifty times per second I'm not sure this will make any practical difference!  But it does remove the subtraction of two from the delay.

**Comment by mungre** [comment]
Thanks, I've incorporated half of your fix.
